name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # update tiap 12 jam
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: snake-animation
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Tailwind Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ZaganJade
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#3B82F6&color_dots=#BFDBFE,#93C5FD,#60A5FA,#3B82F6,#1E40AF
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#38BDF8&color_dots=#0D1117,#1E3A8A,#3B82F6,#60A5FA,#93C5FD

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
